log_level: debug

database:
  postgres:
    host: localhost
    port: 5432
    user: root
    password: root
    dbname: rindag
    use_ssl: false
  redis:
    host: localhost:6379
    password: ""
    db: 0

storage:
  type: minio
  minio:
    endpoint: localhost:9000
    access_key_id: minio
    secret_access_key: minio123
    use_ssl: true
    bucket: rindag

git:
  repo_dir: /var/lib/rindag/git/

judges:
  local1:
    host: localhost:5051
    token: ""

compile:
  cmd: ["/usr/bin/g++", "-std=c++17", "-O2"]
  time_limit: 10000000000
  memory_limit: 256000000
  stderr_limit: 1024

validator:
  compile:
    args: []
  run:
    time_limit: 10000000000
    memory_limit: 256000000
    stderr_limit: 1024

checker:
  compile:
    args: []
  run:
    time_limit: 10000000000
    memory_limit: 256000000
    stderr_limit: 1024

generator:
  compile:
    args: []
  run:
    time_limit: 10000000000
    memory_limit: 256000000
    stderr_limit: 1024
